github:
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-community/rust-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/cargo","gcr.io/paketo-buildpacks/cargo"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:         Tini
  id:           tini
  uses:         docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       tini-amd64
    owner:      krallin
    repository: tini
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}