api = "0.6"

[buildpack]
  id = "paketo-community/cargo"
  name = "Rust Cargo Build Pack"
  version  = "{{.version}}"
  homepage = "https://github.com/paketo-community/cargo"
  description = "A Cloud Native Buildpack that builds Cargo-based Rust applications from source"
  keywords    = ["cargo", "rust", "build-system"]

[[buildpack.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/paketo-community/cargo/blob/main/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"

[[metadata.configurations]]
name        = "BP_CARGO_INSTALL_ARGS"
description = "additional arguments to pass to Cargo install"
default     = ""
build       = true

[[metadata.configurations]]
name        = "BP_CARGO_WORKSPACE_MEMBERS"
description = "the subset of workspace members for Cargo to install"
default     = ""
build       = true

[[metadata.configurations]]
name        = "BP_CARGO_EXCLUDE_FOLDERS"
description = "folders that should not be deleted and should persist to the generated image"
default     = "static, templates, public, html"
build       = true

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]