// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	pexec "github.com/paketo-buildpacks/packit/pexec"
	mock "github.com/stretchr/testify/mock"
)

// Executable is an autogenerated mock type for the Executable type
type Executable struct {
	mock.Mock
}

// Execute provides a mock function with given fields: execution
func (_m *Executable) Execute(execution pexec.Execution) error {
	ret := _m.Called(execution)

	var r0 error
	if rf, ok := ret.Get(0).(func(pexec.Execution) error); ok {
		r0 = rf(execution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
