// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Build provides a mock function with given fields: workDir
func (_m *Runner) Build(workDir string) error {
	ret := _m.Called(workDir)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(workDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
