// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	packit "github.com/paketo-buildpacks/packit"
	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Install provides a mock function with given fields: srcDir, workLayer, destLayer
func (_m *Runner) Install(srcDir string, workLayer packit.Layer, destLayer packit.Layer) error {
	ret := _m.Called(srcDir, workLayer, destLayer)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, packit.Layer, packit.Layer) error); ok {
		r0 = rf(srcDir, workLayer, destLayer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
