// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Summer is an autogenerated mock type for the Summer type
type Summer struct {
	mock.Mock
}

// Sum provides a mock function with given fields: path
func (_m *Summer) Sum(path ...string) (string, error) {
	_va := make([]interface{}, len(path))
	for _i := range path {
		_va[_i] = path[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(...string) string); ok {
		r0 = rf(path...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(path...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
